base.url=https://tbcbank.ge
api.url=https://apigw.tbcbank.ge
site.id=QmI6EfBbkDQ9awR6nBYXx
browser=chromium
headless=true
slow.mo=0
viewport.width=1440
viewport.height=900
default.timeout=15000
navigation.timeout=45000
assertion.timeout=15000
block.third.party=true
db.url=jdbc:h2:mem:tbc_test_data;DB_CLOSE_DELAY=-1;MODE=MSSQLServer
db.username=sa
db.password=
